### ISSUE TITLE
pnv:has_name property ... bestaat dat? 

### ISSUE THREAD

**Issue by phpetra** [Stadsarchief-Amsterdam/blauwdruk#13]
En anders: een path met een underscore, hadden we nog niet, dacht ik? Ik vin deht vereemde syntax, wat wil je ermee uitdrukken?

https://github.com/Stadsarchief-Amsterdam/blauwdruk/blob/284d99269b9832878be400467438493e3174a21e/memorix-recordtypes/Persoonsvermelding.ttl#L65

**Comment by ivozandhuis** [comment]
Je hebt gelijk: ik heb verkeerd gekeken. Moet zijn:
https://w3id.org/pnv#hasName
